# Generated by Django 5.2.8 on 2025-11-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('rfid_tag', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('parent_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
