# Generated by Django 5.2.8 on 2025-11-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_entry_time', models.DateTimeField(blank=True, null=True)),
                ('last_exit_time', models.DateTimeField(blank=True, null=True)),
                ('present', models.BooleanField(default=False)),
            ],
        ),
    ]
