# Generated by Django 5.2.8 on 2025-12-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="approval_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="approved_by",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="override_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="verification_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
